Repository instructlab/ci-actions, pull requests merged in 2025-05, with the labels that each got.

#18 fix(launch-ec2-runner-with-fallback): Always check if an instance is launched + perform cleanup
  actions/launch-ec2-runner-with-fallback/action.yml
Labels: one-approval

#15 feat: move validate notebooks action
  README.md
  actions/validate-notebooks/action.yml
  actions/validate-notebooks/validate-notebooks.md
  actions/validate-notebooks/validate.py
Labels: CI/CD, documentation, one-approval

#12 chore: run action tests when calling `tox`
  tox.ini
Labels: CI/CD, testing, one-approval

#26 feat: use `uv pip compile` for update-constraints
  actions/update-constraints/generate_constraints.sh
  actions/update-constraints/update-constraints.md
Labels: one-approval
